name: Clong 的博客
description: 记录发生在身边的点滴小事。
meta_description: "Clong的博客，记录发生在身边的点滴小事"

markdown: redcarpet
pygments: true
logo: false
paginate: 5

# Details for the RSS feed generator
url:            'clongbupt.github.io'
author:         'clongbupt'
